openapi: 3.1.0
info:
  title: Ask API
  version: 1.0.0
paths:
  /ask:
    post:
      operationId: askSomething
      summary: Ask a question to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
      responses:
        '200':
          description: Answer from the system
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
