openapi: 3.0.3
info:
  title: GuruGPT Plugin API
  description: An API that allows GPT to retrieve answers from the Guru knowledge base.
  version: "1.0.0"

servers:
  - url: https://guru-plugin-api-csherin.replit.app

paths:
  /ask:
    post:
      summary: Ask a question to Guru
      operationId: askGuru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The user's question
              required:
                - question
      responses:
        '200':
          description: Successful response from Guru
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: object
                    properties:
                      answerId:
                        type: string
                      text:
                        type: string
                      sources:
                        type: array
                        items:
                          type: object
                          properties:
                            title:
                              type: string
                            url:
                              type: string
        '400':
          description: Bad Request — missing question
        '401':
          description: Authentication failed
        '500':
          description: Internal server error
